name: website_proj_2
description: "A portfolio website for Helmi Hernandez."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/projects/unity_pic_1.png
    - assets/projects/unity_pic_2.png
    - assets/projects/flutter_firebase.png
    - assets/icons/
